In [1]:
import re
import pandas as pd
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB,MultinomialNB,GaussianNB
from sklearn.linear_model import LogisticRegression,SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline

In [2]:
sws=list(ENGLISH_STOP_WORDS)
sws.remove("not")
sws.remove("no")
for w in sws:
    if w.endswith("n't"):
        sws.remove(w)

def text_cleaning(doc):
    newdoc=re.sub(r"[^a-z0-9\s']",'',doc.lower())
    words=newdoc.split()
    newdoc=[]
    for word in words:
        if word not in sws:
            newdoc.append(word)
    return ' '.join(newdoc)

In [4]:
df=pd.read_csv('c:/ml_datasets/Restaurant_Reviews.txt',sep='\t')
df.Review=df.Review.apply(text_cleaning)
df

                                                Review  Liked
0                                      wow loved place      1
1                                       crust not good      0
2                         not tasty texture just nasty      0
3    stopped late bank holiday rick steve recommend...      1
4                          selection menu great prices      1
..                                                 ...    ...
995                  think food flavor texture lacking      0
996                            appetite instantly gone      0
997                          overall not impressed not      0
998  experience underwhelming think we'll just ninj...      0
999  hadn't wasted life poured salt wound drawing t...      0

[1000 rows x 2 columns]

In [5]:
corpus=df.Review
target=df.Liked

In [6]:
#combination-1
tv=TfidfVectorizer()
X=tv.fit_transform(corpus).toarray()
print(len(tv.get_feature_names_out()))

model=MultinomialNB()
d=cross_validate(model,X,target,cv=5,return_train_score=True)
print(d['train_score'].mean())
print(d['test_score'].mean())

1852
0.9665000000000001
0.8029999999999999

In [7]:
#combination-2
tv=TfidfVectorizer()
X=tv.fit_transform(corpus).toarray()
print(len(tv.get_feature_names_out()))

model=LogisticRegression()
d=cross_validate(model,X,target,cv=5,return_train_score=True)
print(d['train_score'].mean())
print(d['test_score'].mean())

1852
0.96075
0.825

In [8]:
df['num_chars']=df.Review.apply(len)
df

                                                Review  Liked  num_chars
0                                      wow loved place      1         15
1                                       crust not good      0         14
2                         not tasty texture just nasty      0         28
3    stopped late bank holiday rick steve recommend...      1         57
4                          selection menu great prices      1         27
..                                                 ...    ...        ...
995                  think food flavor texture lacking      0         33
996                            appetite instantly gone      0         23
997                          overall not impressed not      0         25
998  experience underwhelming think we'll just ninj...      0         58
999  hadn't wasted life poured salt wound drawing t...      0         66

[1000 rows x 3 columns]

In [9]:
df1=df[df.num_chars>0]

In [10]:
corpus=df1.Review
target=df1.Liked

In [11]:
#combination-1
tv=TfidfVectorizer(max_features=660)
X=tv.fit_transform(corpus).toarray()
print(len(tv.get_feature_names_out()))

model=MultinomialNB()
d=cross_validate(model,X,target,cv=5,return_train_score=True)
print(d['train_score'].mean())
print(d['test_score'].mean())

660
0.9261059406965473
0.8196783919597991

In [12]:
#combination-2
tv=TfidfVectorizer(max_features=660)
X=tv.fit_transform(corpus).toarray()
print(len(tv.get_feature_names_out()))

model=LogisticRegression()
d=cross_validate(model,X,target,cv=5,return_train_score=True)
print(d['train_score'].mean())
print(d['test_score'].mean())

660
0.9296115758733503
0.824678391959799

In [13]:
#online training
tv=TfidfVectorizer(max_features=660)
X=tv.fit_transform(corpus).toarray()
print(len(tv.get_feature_names_out()))

y=target

660

In [14]:
X.shape

(998, 660)

In [15]:
y.shape

(998,)

In [16]:
X1=X[:500,:]
y1=y[:500]

X2=X[500:,:]
y2=y[500:]

In [17]:
X1.shape

(500, 660)

In [18]:
X2.shape

(498, 660)

In [19]:
model=MultinomialNB()
model.partial_fit(X1,y1,classes=[0,1])
model.score(X,y)

0.8276553106212425

In [20]:
model.partial_fit(X2,y2)
model.score(X,y)

0.9198396793587175

In [21]:
df2=pd.read_csv('c:/ml_datasets/more_reviews_restaurant.csv',sep='\t')
df2

                                                Review  Liked
0    {Item} was cold and lacked flavor. Not worth t...      0
1          Poor service and amazing hygiene standards.      0
2       Overpriced and terrible. Wouldn’t visit again.      0
3    Nothing tasted disappointing. The place smelle...      0
4    Everything was on point — from salads to cake....      1
..                                                 ...    ...
995  Everything was on point — from salads to ice c...      1
996  Highly recommend trying the burger. Simply dis...      1
997       Poor service and friendly hygiene standards.      0
998  This is my go-to place for soup. Never disappo...      1
999  Would definitely come again. Loved the present...      1

[1000 rows x 2 columns]

In [22]:
df1=pd.read_csv('c:/ml_datasets/Restaurant_Reviews.txt',sep='\t')
df2=pd.read_csv('c:/ml_datasets/more_reviews_restaurant.csv',sep='\t')
final_df=pd.concat([df1,df2],ignore_index=True)
final_df

                                                 Review  Liked
0                              Wow... Loved this place.      1
1                                    Crust is not good.      0
2             Not tasty and the texture was just nasty.      0
3     Stopped by during the late May bank holiday of...      1
4     The selection on the menu was great and so wer...      1
...                                                 ...    ...
1995  Everything was on point — from salads to ice c...      1
1996  Highly recommend trying the burger. Simply dis...      1
1997       Poor service and friendly hygiene standards.      0
1998  This is my go-to place for soup. Never disappo...      1
1999  Would definitely come again. Loved the present...      1

[2000 rows x 2 columns]

In [24]:
df1=pd.read_csv('c:/ml_datasets/Restaurant_Reviews.txt',sep='\t')
df2=pd.read_csv('c:/ml_datasets//more_reviews_restaurant.csv',sep='\t')
final_df=pd.concat([df1,df2],ignore_index=True)

sws=list(ENGLISH_STOP_WORDS)
sws.remove("not")
sws.remove("no")
for w in sws:
    if w.endswith("n't"):
        sws.remove(w)

def text_cleaning(doc):
    newdoc=re.sub(r"[^a-z0-9\s']",'',doc.lower())
    words=newdoc.split()
    newdoc=[]
    for word in words:
        if word not in sws:
            newdoc.append(word)
    return ' '.join(newdoc)

final_df.Review=final_df.Review.apply(text_cleaning)
final_df['num_char']=final_df.Review.apply(len)
final_df=final_df[final_df.num_char>=5]

In [25]:
corpus=final_df.Review
target=final_df.Liked

tv=TfidfVectorizer(max_features=1000)
X=tv.fit_transform(corpus).toarray()
print(tv.get_feature_names_out().shape)
model=MultinomialNB(alpha=.8)
d=cross_validate(model,X,target,cv=5,return_train_score=True)
print(d['train_score'].mean())
print(d['test_score'].mean())

(1000,)
0.9587939698492463
0.8904522613065327

In [26]:
model=MultinomialNB(alpha=.8)
model.fit(X,target)

MultinomialNB(alpha=0.8)

In [27]:
sample="food was not tasty"

In [29]:
df1=pd.read_csv('c:/ml_datasets/Restaurant_Reviews.txt',sep='\t')
df2=pd.read_csv('c:/ml_datasets/more_reviews_restaurant.csv',sep='\t')
final_df=pd.concat([df1,df2],ignore_index=True)

corpus=final_df.Review
target=final_df.Liked

sws=list(ENGLISH_STOP_WORDS)
sws.remove("not")
sws.remove("no")
for w in sws:
    if w.endswith("n't"):
        sws.remove(w)

tv=TfidfVectorizer(lowercase=True,stop_words=sws)
pipe=Pipeline([('pre_vect',tv),('model',MultinomialNB())])
pipe.fit(corpus,target)

Pipeline(steps=[('pre_vect',
                 TfidfVectorizer(stop_words=['con', 'is', 'others', 'perhaps',
                                             'are', 'the', 'five', 'onto',
                                             'being', 'whom', 'through',
                                             'further', 'thick', 'whatever',
                                             'call', 'seem', 'fifty', 'hereby',
                                             'her', 'please', 'amoungst',
                                             'however', 'almost', 'yours',
                                             'twenty', 'below', 'thence',
                                             'only', 'ever', 'eg', ...])),
                ('model', MultinomialNB())])

In [30]:
import joblib

In [32]:
joblib.dump(pipe,"review_of_rstron.pkl")

['review_of_rstron.pkl']